# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chapitre.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1051, 818)
        Dialog.setStyleSheet("")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 20, 93, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.labelChapitreNo = QtWidgets.QLabel(Dialog)
        self.labelChapitreNo.setGeometry(QtCore.QRect(340, 10, 311, 101))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.labelChapitreNo.setFont(font)
        self.labelChapitreNo.setTextFormat(QtCore.Qt.AutoText)
        self.labelChapitreNo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelChapitreNo.setObjectName("labelChapitreNo")
        self.labelNumeroChapitre = QtWidgets.QLabel(Dialog)
        self.labelNumeroChapitre.setGeometry(QtCore.QRect(610, 10, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Viner Hand ITC")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.labelNumeroChapitre.setFont(font)
        self.labelNumeroChapitre.setText("")
        self.labelNumeroChapitre.setTextFormat(QtCore.Qt.AutoText)
        self.labelNumeroChapitre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNumeroChapitre.setObjectName("labelNumeroChapitre")
        self.labelTexteChapitre = QtWidgets.QLabel(Dialog)
        self.labelTexteChapitre.setGeometry(QtCore.QRect(50, 110, 971, 601))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setItalic(False)
        self.labelTexteChapitre.setFont(font)
        self.labelTexteChapitre.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.labelTexteChapitre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelTexteChapitre.setScaledContents(True)
        self.labelTexteChapitre.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTexteChapitre.setWordWrap(True)
        self.labelTexteChapitre.setObjectName("labelTexteChapitre")
        self.pushButtonChoixChapitre = QtWidgets.QPushButton(Dialog)
        self.pushButtonChoixChapitre.setGeometry(QtCore.QRect(630, 740, 81, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonChoixChapitre.setFont(font)
        self.pushButtonChoixChapitre.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonChoixChapitre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButtonChoixChapitre.setObjectName("pushButtonChoixChapitre")
        self.plainTextChoixChapitre = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextChoixChapitre.setGeometry(QtCore.QRect(440, 740, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.plainTextChoixChapitre.setFont(font)
        self.plainTextChoixChapitre.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.plainTextChoixChapitre.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plainTextChoixChapitre.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.plainTextChoixChapitre.setObjectName("plainTextChoixChapitre")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "SAUVEGARDE"))
        self.labelChapitreNo.setText(_translate("Dialog", "Chapitre N°"))
        self.labelTexteChapitre.setText(_translate("Dialog", "TextLabel"))
        self.pushButtonChoixChapitre.setText(_translate("Dialog", "GO"))
